name: Deploy to Github Pages

on:
  push:
    branches:
      - main

env:
  GITHUB_PAGES_BUILD_FOLDER: client
  PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Start server
      run: |
        node svr.mjs
      env:
        GITHUB_PAGES_BUILD_FOLDER: ${{ env.GITHUB_PAGES_BUILD_FOLDER }}
        PORT: ${{ env.PORT }}
      timeout-minutes: 1
