name: Deploy to Github Pages

on:
  push:
    branches:
      - main

env:
  PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Start server
      run: node svr.mjs

    - name: Deploy to Github Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"
        git clone https://github.com/${{ github.repository }}.git deploy
        cd deploy
        rm -rf client
        cp -rf ../client .
        git add .
        git commit -m "Deploy ${{ env.GITHUB_SHA }}"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
